services:

  frontend:
    image: pranav7820/nadsoft-frontend:latest
    ports:
      - "3000:3000"
    depends_on:
      - backend

  backend:
    image: pranav7820/nadsoft-backend:latest
    ports:
      - "5000:5000"
    depends_on:
      mysql:
        condition: service_healthy
    env_file:
      - ./nadsoft-backend/.env
    environment:
      - DB_HOST=mysql

  mysql:
    image: mysql:8
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: nadsoft
    ports:
      - "3307:3306"
    volumes:
      - mysql-data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 10

volumes:
  mysql-data:
